classic/readme.md
lightning/readme.md

bump version to v5.7

---

lightning/02 Installation/02 Installing the Amazon Connect Salesforce Lambda Package.md

Update 02 Installing the Amazon Connect Salesforce Lambda Package.md

---

classic/02 Installation/02 Installing the Amazon Connect Salesforce Lambda Package.md
lightning/02 Installation/02 Installing the Amazon Connect Salesforce Lambda Package.md

clarify correct url pattern for SalesforceHost lambdas cf parameter

---

README.md

fix version date

---

classic/02 Installation/02 Installing the Amazon Connect Salesforce Lambda Package.md
lightning/02 Installation/02 Installing the Amazon Connect Salesforce Lambda Package.md

fix API_ONLY profile settings steps

---

lightning/04 Configuring and Using AWS Serverless Application Repository for Salesforce Features/04 Contact Channel Analytics.md

clarify CORS configuration AllowedOrigin value

---

classic/01 Introduction/01 Key Benefits and Requirements.md
classic/02 Installation/01 Installing the Amazon Connect CTI Adapter for Salesforce Package.md
lightning/02 Installation/01 Installing CTI Adapter Managed Package from AppExchange.md
lightning/readme.md

Changing instances of whitelist to allowlist

---

lightning/04 Configuring and Using AWS Serverless Application Repository for Salesforce Features/02 Amazon Connect Historical Metrics in Salesforce.md

Update 02 Amazon Connect Historical Metrics in Salesforce.md

---

README.md
classic/readme.md
lightning/readme.md

Add docs for 5.11

---

classic/readme.md
lightning/readme.md

fix v5.10 release date, update pdf

---

classic/02 Installation/03 Upgrading from an Earlier Version.md
lightning/02 Installation/03 Upgrading from an Earlier Version.md

clarify which upgrade paths need to follow additional setup steps

---

classic/readme.md
lightning/03 Configuring and Using CTI Adapter Features/05 Set Agent Status on Session End.md
lightning/readme.md

V5 12 documentation

---

lightning/03 Configuring and Using CTI Adapter Features/07 CTI Actions.md

This describes a process for how to change the layout for CTI Script object. This will display the CTI Action in the dropdown.

Add section for upgrading from a previous version CTI Actions

---

README.md
docusaurus.config.js
package.json

some fixes and improvements

---

docs/classic/release-notes.md
docs/lightning/release-notes.md

Adding v5.13 bugfix to release notes

---

docs/classic/03-cti-adapter/04-call-recording-link-for-task.md
docs/lightning/04-salesforce-lambdas/04-contact-channel-analytics.md

fix sfSig4RequestToS3 link

---

docusaurus.config.js

add search to documentation website

---

docs/classic/02-installation/04-cti-adapter-installation-troubleshooting.md
docs/lightning/02-installation/04-adapter-installation-troubleshooting.md

remove duplicate entry from the troubleshooting page

---

docs/classic/03-cti-adapter/01-cti-adapter-configuration.md
docs/classic/05-appendices/02-appendix-b-configuring-salesforce-as-your-identity-provider/01-configuring-salesforce-as-your-identity-provider.md
docs/lightning/03-cti-adapter/01-cti-adapter-configuration.md
docs/lightning/04-salesforce-lambdas/04-contact-channel-analytics.md
docs/lightning/04-salesforce-lambdas/05-contact-trace-record-import.md
docs/lightning/05-appendices/appendix-b-configuring-salesforce-as-your-identity-provider/01-configuration.md

Adding note about CTI Adapter configuration with SAML

---

docs/lightning/04-salesforce-lambdas/04-contact-channel-analytics.md

Adding clarification for Contact Channel Analytics Setup

---

package.json

address github security alerts

---

docs/lightning/03-cti-adapter/06-set-agent-status-on-session-end.md

Adding documentation for SessionEndTimer feature

---

docs/classic/03-cti-adapter/12-chat-widget-integration.md
docs/classic/release-notes.md
docs/lightning/03-cti-adapter/11-chat-widget-integration.md
docs/lightning/release-notes.md

update doc for postinstall handler removal

---

docs/lightning/05-appendices/appendix-e-salesforce-high-velocity-sales/01-high-velocity-sales.md

fix misleading steps in HVS setup

---

docs/classic/02-installation/03-managed-package-manual-setup.md
docs/classic/release-notes.md
docs/lightning/02-installation/03-managed-package-manual-setup.md
docs/lightning/release-notes.md

add more warnings for admin install to make it harder to miss

---

package-lock.json
package.json

see [here](https://github.com/amazon-connect/amazon-connect-salesforce-cti/security/dependabot)
this won't remediate all issues unfortunately because some dependencies require vulnerable versions

remdiate security issues in npm dependencies

---

docs/classic/release-notes.md
docs/lightning/release-notes.md

Adding note about plan-b deprecation

---

docs/classic/release-notes.md
docs/lightning/release-notes.md

v5.18 release notes

---

docs/classic/release-notes.md
docs/lightning/release-notes.md

Adding note about spring '22 release

---

docs/classic/04-salesforce-lambdas/01-contact-flow-salesforce-lambdas.md
docs/classic/release-notes.md
docs/lightning/04-salesforce-lambdas/01-contact-flow-salesforce-lambdas.md
docs/lightning/release-notes.md

Adding documentation for v5.18 lambda changes

Add documentation for lambda changes for v5.18

---

docs/other/earlier-versions.md
docusaurus.config.js

Update version in header and add 5.17 in earlier versions

Update version in header and add 5.17 in earlier versions

---

docs/classic/03-cti-adapter/01-cti-adapter-configuration.md
docs/classic/05-appendices/02-appendix-b-configuring-salesforce-as-your-identity-provider/01-configuring-salesforce-as-your-identity-provider.md
docs/lightning/03-cti-adapter/01-cti-adapter-configuration.md
docs/lightning/05-appendices/appendix-b-configuring-salesforce-as-your-identity-provider/01-configuration.md

have users specify region of the RelayState url

---

docs/classic/release-notes.md
docs/lightning/release-notes.md

Adding additional note about installing for admin

---

docs/classic/release-notes.md
docs/lightning/release-notes.md

*Description of changes:* The PR is to update the release notes to add information about Enhanced Domains. The linked asana ticket is: https://app.asana.com/0/1201248563835287/1202858230200699/f

Updated release notes with information of enhanced domains

---

package-lock.json

https://github.com/amazon-connect/amazon-connect-salesforce…

fix ReDoS issue 

---

docs/classic/release-notes.md
docs/lightning/release-notes.md

* Adds libphonenumber-js updates to documentation
* Resolves rebase conflicts, moves libphonenumber update to general notes section
We did an upgrade on a library responsible for parsing phone numbers a couple releases ago. This will help to clarify the changes users may need to make to avoid impact.

Adds libphonenumber-js updates to documentation (#157)

---

docs/lightning/release-notes.md

*Description of changes:* update 5.27 release notes

update 5.27 release notes
